incubateur-ademe/nosgestesclimat-site

- package.json
La décision n'est pas encore complètement arrêtée, mais en attendant on
se fixe sur le nom de l'outil déjà connu "Micmac"
> Passage de apps/climat à apps/micmac

- source/components/SessionBar.tsx
- source/components/ShareButton.js
- source/components/Simulation.tsx
- source/sites/publicodes/App.js
- source/sites/publicodes/Contribution.js
- source/sites/publicodes/Fin.js
- source/sites/publicodes/Simulateur.js
- source/sites/publicodes/chart/Bar.js
- source/sites/publicodes/chart/Value.js
- source/sites/publicodes/chart/index.js
Pour l'instant je pars sur cet encodage : /fin?total=8097&détails=a3.23t2.12s1.56l1.56b1.12f0.08n0.34
Comme ça le total reste lisible, et les détails sont encodés à la fin de la façon la plus courte possible, sans perdre trop de détail.
Fixes betagouv/ecolab-data/issues/50
> Ecran de fin v2, avec le graphique

- source/RulesProvider.js
Et on s'attend désormais à ce que les deux dépots soient au même niveau,
comme c'était documenté.
> Adaptation du code pour charger en dev plusieurs yaml

- source/sites/publicodes/Landing.js
Pour enlever toute ambiguïté, malgré le nom de domaine en .ademe.fr
> Logo ademe

- package.json
- source/components/SessionBar.tsx
- source/components/Simulation.tsx
- source/components/conversation/Conversation.tsx
- source/components/conversation/InputEstimation.tsx
- source/sites/publicodes/Action.js
- source/sites/publicodes/Actions.js
- source/sites/publicodes/Fin.js
- source/sites/publicodes/Landing.js
- source/sites/publicodes/Simulateur.js
- source/sites/publicodes/VersionBeta.js
- yarn.lock
Suite de #58 
Objectif 1 ✔ : démo du mardi 30 juin
Objectif 2 ✔ : fiches dynamiques, reposant sur le modèle et les données utilisateur
Objectif 3 : des fiches utiles pour l'utilisateur
On en est où ? J'ai fait pas mal de remarques sur https://github.com/betagouv/ecolab-data/pull/581
Au-delà des remarques auxquelles j'attends une réponse, il faut que les actions puissent entraîner des questions pour traiter les questions sur le trajet dom-tra et les vacances.
Notamment, finaliser les fiches humour et les 110km/h, ou les virer.
> Fiches action

- source/webpack.common.js
> 2ème essai
C'est carré sur twitter, donc le logo Nos Gestes Climat n'est pas
lisible.
Et puis souvent, l'image de partage n'est pas le logo, mais
l'illustration de l'article.
J'ai aussi changé le texte pour mettre des majuscules et enlever "Ecolab"
> Changement de l'image de partage pour le dessin

- source/sites/publicodes/Actions.js
Le mode guidé permet de voir un programme progressif, je pense qu'il est
bien de classer le mode autonome inversement par défaut.
> Passage à un tri décroissant pour les actions du mode autonome

- source/sites/publicodes/App.tsx
- source/sites/publicodes/about.md
@martinregner le lien "vie privée" faisait référence à un composant pas branché sur l'URL /vie-privée, par erreur. J'ai corrigé ça en voyant ton commit :)
> :bug: Mauvais composant pour l'URL vie privée

- source/sites/publicodes/Fin.js
Reverts datagir/nosgestesclimat-site#299
Je reviens en arrière, car ça ne fonctionne pas. Le serveur de cache d'image semble bien être nécessaire, sans que je ne sache trop pour quoi. Sûrement une question de délai. Peut-être que le premier appel du réseau social lance la mise en cache, puis l'appel vers l'image est plus rapide ?
> Revert "Gen image fin"

- source/components/conversation/mosaicQuestions.ts
Correction d'une faute de frappe. Il manque le poisson et non le poison ! 👍
> ✏️  Correction faute de frappe

- source/sites/publicodes/personas.yaml
Persona pour mettre en avant la limite des actions transports et le besoin pour NGC : 
- d'identifier cette limite
- de porter un message du type "peu de levier d'action directe et donc action indirecte / nécessité de transition globale"
> nouveaux personas

- source/components/conversation/select/NumberedMosaic.tsx
Fixes datagir/nosgestesclimat/issues/1284
> :bug: Nombre >= 10 s'affiche pas dans la mosaique iPhone

- source/sites/publicodes/personas.yaml
La modification de sélection des modes de chauffages n'avait pas été pris en compte pour les personas. Notamment le 2kg qui passait du coup à 3.8kg
> Correction chauffage des personas

- source/sites/publicodes/conference/Survey.tsx
Pour résoudre le problème soulevé par @martinregner dans https://github.com/datagir/nosgestesclimat-server/issues/2.
Désormais, on vérifie que le sondage est bien dans la table "surveys" avant de proposer le lien de téléchargement pour éviter les bugs.
Je vous laisse relire (syntaxe/typo et on merge ;) )
> Amélioration message export sondage

- source/components/conversation/Input.tsx
Afin de formater les valeurs par défaut des inputs lorsqu'elles sont calculées.
Avant:
> formatvalue pour les valeurs par défaut

- source/components/conversation/Conversation.tsx
- source/components/conversation/mosaicQuestions.ts
**Pb actuel :** Aujourd'hui, au niveau d'une mosaïque, le bouton suivant apparait directement. Pour les mosaïques "select" Les valeurs par défaut sont bien pré-sélectionnées mais au clic sur suivant, elles sont mises à 0 si defaulttofalse est activé -> ce qui est attendu car rien n'est coché ! Seul échappe permet d'ajouter les valeurs par défaut à la situation mais on pourrait aussi supposé qu'une personne souhaite répondre rapidement ou clique sur suivant trop vite.
**Solution :** Je propose ici d'ajouter le bouton "je ne sais pas" qui permet de valider les valeurs par défaut (certes non explicite pour l'utilisateur) qui disparait si l'une des cases est coché. Le bouton suivant ne valide toujours "rien" s'il est cliqué en premier. Si une réponse est cochée, toutes les valeurs par défaut …
> Ré-introduction du bouton "Je ne sais pas" dans les mosaïques

- source/components/Notifications.tsx
- source/components/conversation/Conversation.tsx
- source/components/utils/EngineContext.tsx
Pour faire suite à #601 
Démo : https://notification-invalid-input-value--nosgestesclimat.netlify.app/?PR=1454
Je remets le dernier commentaire de la PR ici :
Je mets en ligne cette PR car elle résout des problèmes majeurs pour l'aide à la saisie des km et permet d'être plus rigoureux sur les inputs des questions de la conversation, sans l'introduction de filtre pour ces inputs pour le moment.
> La gestion de l'input de la conversation est assez compliquée car on souhaite que le submit reste général.
> Plusieurs solutions envisagées pour vérifier l'input et permettre ou non sa validation :
>
> - Une fonction de validation définie dans Input et appelée et exécutée dans le submit de Conversation (en affichant un warning sur l'input)
> - Une variable dans le state initialisée à true qui …
> Notification 'invalide' pour filtrer les inputs

- source/RulesProvider.js
- source/components/localisation/Localisation.tsx
- source/components/localisation/supportedCountries.yaml
- source/components/localisation/useLocalisation.ts
- source/components/publicodesUtils.js
- source/components/useBranchData.ts
- source/reducers/rootReducer.ts
- source/sites/publicodes/LandingExplanations.tsx
- Clef react manquante
- Relique d'un essai pour gérer le parsing des règles
C'est à cause de `const loaded = pullRequestNumber != undefined ` qui ignore shouldUseLocalFiles, faut refaire ça de façon cohérente.
> nettoyage et gros bug localisation -> "chargement du moteur"

- source/sites/publicodes/Landing.js
- source/sites/publicodes/Personas.tsx
- source/sites/publicodes/Profil.tsx
Une proposition pour améliorer la visibilité du bouton pour "retrouver" sa simulation dès la landing
Démo: https://position-bouton-profil-landing--nosgestesclimat.netlify.app/
> Position bouton profil sur la Landing

- source/components/stats/StatsContent.js
- source/components/stats/content/Chart.js
- source/components/stats/content/Evolution.js
- source/components/stats/content/IframeFigures.js
- source/components/stats/content/KmFigures.js
- source/components/stats/content/ScoreFromURL.js
- source/components/stats/content/TotalChart.js
- source/components/stats/content/chart/CustomTooltip.js
- source/components/stats/content/histogram/CustomTooltip.js
- source/components/stats/content/sources/Table.js
- source/components/stats/matomo.js
- source/components/stats/utils/Section.js
- source/components/stats/utils/Tile.js
- source/components/utils/IframeOptionsProvider.tsx
- source/sites/publicodes/fin/index.tsx
- source/sites/publicodes/iframe.js
Démo : https://ameliorations-page-stats--nosgestesclimat.netlify.app/stats
> Améliorations page stats

- source/components/stats/content/ScoreFromURL.js
To retrieve final scores from urls, we need to look only for ones containing a `?details=` query string param.
> fix(stats): to calculate score, end pages need to have a details param

- source/locales/pages/en-us/diffuser.md
- source/locales/pages/fr/diffuser.md
Add a new section to the `/diffuser` page:
French version:
English version:
> Docs: new section in the /diffuser page

- index.html
- source/components/utils/Meta.tsx
Selon cette documentation https://developers.google.com/search/docs/advanced/crawling/localized-versions?hl=fr
Je ne sais pas si on devrait rendre dynamiques ces tags via Meta.tsx, ou
vu que l'on est une SPA, peut-être que ça suffit ainsi ?
C'est de toutes façons mieux ainsi
> Ajout des tags de langage pour Google & co

- source/sites/publicodes/HumanWeight.js
Je pense que l'affichage au dixième de kg de CO2e n'est pas utile dans NGC, je propose d'arrondir au kg près (d'autant que la précision n'est pas cohérente avec la précision en tonnes
> précision inutile kg

- source/locales/units.yaml
Dans la partie "âge du véhicule", typo identifiée
> Typo "annnées" --> "année"

- source/locales/ui/ui-en-us.yaml
- source/locales/ui/ui-fr.yaml
- source/sites/publicodes/conference/Conference.tsx
- source/sites/publicodes/conference/ConferenceBar.tsx
- source/sites/publicodes/conference/Instructions.tsx
- source/sites/publicodes/conference/NoSurveyCreatedWarning.tsx
- source/sites/publicodes/conference/Stats.tsx
- source/sites/publicodes/conference/Survey.tsx
- source/sites/publicodes/conference/SurveyBar.tsx
- source/sites/publicodes/conference/utils.tsx
> :video_game:  Pas possible de tester le mode sondage en ligne sur la démo, malheureusement :/
> Pour une explication grand public des améliorations, voir le brouillon de release ici https://github.com/datagir/nosgestesclimat/releases/tag/untagged-b699f9073d0a66db27a8
> Amélioration de la visibilité du nombre participants sur les modes groupe

- source/sites/publicodes/conference/Stats.tsx
Y compris quand le test n'est pas fini. C'était l'objet de la dernière
PR, mais cette partie là m'avait échappé car je testais l'interface
uniquement via les personas, qui sont tous terminés.
> :bug: Sur l'écran de stats du mode groupe, on affiche tous les éléments

- source/components/conversation/estimate/AnswerTrajetsTable.js
En production, il m'est impossible d'ouvrir la sous-catégorie "Voiture" dans la catégorie "Transport" parce qu'une traduction n'est pas correctement chargée.
Le résultat est une page complètement blanche et une belle erreur dans la console.
> 🐛 Traduction manquante qui empêche l'ouverture de la sous-catégorie "Voiture" depuis la page "Mon profil"

- scripts/fetch-releases.js
- source/sites/publicodes/conference/useYjs.tsx
Fixes #875 
On héberge chez nous via https://github.com/datagir/nosgestesclimat-conference
> Nouveau serveur de signalement conférence y-webrtc, chez nous

- source/components/SessionBar.tsx
- source/components/localisation/Localisation.tsx
- source/components/localisation/LocalisationMessage.tsx
- source/images/1F3DF.svg
- source/locales/ui/ui-en-us.yaml
- source/locales/ui/ui-fr.yaml
- source/reducers/rootReducer.ts
- source/selectors/storageSelectors.ts
- source/sites/publicodes/App.tsx
- source/sites/publicodes/Landing.tsx
- source/sites/publicodes/ScoreBar.tsx
- source/sites/publicodes/conference/CategoryStats.tsx
- source/sites/publicodes/conference/Conference.tsx
- source/sites/publicodes/conference/ConferenceBar.tsx
- source/sites/publicodes/conference/GroupModeSessionVignette.tsx
- source/sites/publicodes/conference/Instructions.tsx
- source/sites/publicodes/conference/NamingBlock.tsx
- source/sites/publicodes/conference/Survey.tsx
- source/sites/publicodes/conference/SurveyBar.tsx
- source/sites/publicodes/conference/useYjs.tsx
> :game_die: 
> Démo https://deploy-preview-866--nosgestesclimat.netlify.app/conférence/ma-super-conf-de-test
Pour l'instant, je bosse sur le mode conf, qui est très similaire au mode sondage en termes d'UX, mais qui a l'avantage de marcher en lien de démo. Les deux ont été codé avec un manque de partage de composants, d'où le gain de temps de valider dans le principe le design de l'un avant de faire l'autre. 
- iframeresizer plus nécessaire dans yarn.lock
- Désactivation du bouton personas en mode dev
- Nouvelle entrée menu "groupe"; "Mon profil"-> "Profil"; alignement hz
- Simplification et justesse du texte intro groupe
- Fin de l'affichage du drapeau de région
- Bords arrondis pour la vignette conférence active
- Taille erronée sur bureau pour les entrées du menu
- Changement de style …
> Navigation mode groupe

- source/components/SessionBar.tsx
- source/components/Stamp.tsx
- source/components/conversation/select/NumberedMosaic.tsx
- source/components/conversation/select/SelectDevices.tsx
- source/components/conversation/select/UI.js
- source/components/ui/index.css
New horizontal layout for mosaics in order to manage more items inside mosaics.
* New horizontal layout for mosaic question + some UI factorisation between the `NumberedMosaic` and `SelectDevices` components
* Better width management of the navbar buttons -- https://github.com/datagir/nosgestesclimat-site/pull/855/commits/747a9b56fc154a1260291b04616ea885f8c85df6
* Put inactive cards at the end of the list -- https://github.com/datagir/nosgestesclimat-site/pull/855/commits/f4a8d6192e04c01b81ca31708cc3323c2a7eadc5#885
> New mosaic layout

- source/components/conversation/Conversation.tsx
Permet normalement de résoudre un bug sur le bouton précédent du aux mosaïques 
On revient toujours sur la même mosaïque ici : on revient toujours sur la mosaïque numérique par exemple
> 🐛 Fix bug bouton précédent

- source/components/conversation/Conversation.tsx
Je fix ici un problème avec le bouton précédent:
si on cherchait à revenir sur une question dont la règle n'est plus dans le modèle, ça cassait l'app
Exemple: 'xxx . présent' transformée en 'xxx . nombre'
Précédent vers 'xxx . présent' pourtant des les previousAnswers cassait l'app
> 🐛Fix bouton "précédent"

- source/components/localisation/RegionGrid.tsx
J'ai noté qu'il y avait un souci sur le style des pays à deux mots. J'en ai profité pour passer sur une utilisation de grid pour avec une grille bien carrée.
J'ai aussi ajouté une max-width sur le conteneur des cards de pays pour faciliter la lecture :
> Corrige l'affichage des labels de pays à deux mots, passe à une utilisation de grid

- README.md
- package.json
- source/RulesProvider.tsx
- source/components/localisation/LocalisationProvider.tsx
- source/components/useFetchDocumentation.ts
- source/sites/publicodes/Personas.tsx
- webpack.dev.js
- yarn.lock
Closes #884, by importing local json files in dev mode instead of relying on a local http server.
* Import the `co2-*.json`, `supportedRegions.json`, `personas-*.json` and `contenu-ecrit.json` files in dev mode.
* Remove the `http-server` dependency.
> Feat: re-enable the hot-reloading when working on the model

- source/components/conversation/Conversation.tsx
Fixes  #949
- 1) tester ce fix
- 2) après analyse des résultats sur les stats de demain, enlever des objectifs les tests complétés qui sont faits avec un clic sur un des personas
> Proposition de fix pour nos stats de conversation

- source/components/Logo.tsx
On avait un pb sur la largeur du lien du logo dans le header (sur la page i18n, un clic en haut de la page redirigeais vers la page d'accueil)
> 🐛 fix width logo link

- package.json
- source/sites/publicodes/LandingExplanations.tsx
- source/sites/publicodes/pages/About.tsx
- source/sites/publicodes/pages/Accessibility.tsx
- source/sites/publicodes/pages/CGU.tsx
- source/sites/publicodes/pages/Diffuser.tsx
- source/sites/publicodes/pages/DocumentationContexte.tsx
- source/sites/publicodes/pages/Méthode.tsx
- source/sites/publicodes/pages/PetrogazLanding.tsx
- source/sites/publicodes/pages/Privacy.tsx
- webpack.common.js
- webpack.dev.js
- yarn.lock
Markdown files weren't correctly loaded in dev mode. It was caused by [this changes](https://github.com/datagir/nosgestesclimat-site/commit/47b74a3abad340d86080edc21f5a312831fab3a0#diff-52cf7951fec7ee5c8db1888ab977bc94c938511c211beecca96a1ebb64a4dafaR19-R26).
This PR introduces changes to use the new webpack [Asset Modules](https://webpack.js.org/guides/asset-modules/) instead of the deprecated `raw-loader` in webpack >v5.
> fix(build): markdown loading in dev mode working

- source/components/conversation/Aide.tsx
Qui de toutes façon, du fait d'une mauvaise signature des props, ne marchait pas. 
Alors autant l'enlever, elle n'a semble-t-il manqué à personne. 
Note : le "En savoir plus" s'affichait toujours, mais sans afficher les références :sweat_smile: 
@lbranaa je crois que tu en avais parlé ?
> Suppression des références publicodes de la bulle d'aide de question

- source/components/conversation/Explicable.tsx
- source/components/conversation/Question.tsx
- source/images/info.svg
Je me permets d'ouvrir une nouvelle PR au sujet du style du point info qui retardait la mise en ligne de #905 
L'objectif ici est d'améliorer le style de l'emoji du point info.
> [Clément] Je suis pas ultra convaincu par les emojis natifs pour ce bouton assez structurant mine de rien et visible partout (ou pas assez justement). Le point info de twemoji est peut etre pas optimal mais on pourrait peut etre dans ce cas en faire un custom ?
> [Maël] On a /source/images/info.svg, tu en penses quoi ? On peut le colorier en mauve
> 🎨 Style point info

- source/components/conversation/Conversation.tsx
- source/selectors/simulationSelectors.ts
- Nouveau selecteur pour savoir si un persona a été sélectionné
- On considère qu'une simulation faite via un persona n'est pas un succès
Cette PR répond à une faille potentielle (qu'on a trouvée avec @bjlaa au cours d'une discussion je crois) pour le funnel de mesure de la complétion du test. 
L'événement était déclenché avec le parcours ci-dessous :
- je fais mon test en partie, ou je ne le fais pas du tout
- je vais sur /actions (via la menu probablement)
- je clique sur un persona
- important : je reviens sur le test sur /simulateur/bilan, c'est là que
les événements sont déclenchés
Les événements étaient codés de façon un peu brute, sans prendre en compte cette subtilité du parcours.
> On enlève les personas des chiffres de conversion 

- source/contexts/TrackerContext/Tracker.ts
Suite à une discussion avec Florian, il m'a partagé l'info que ICO2 avait le même problème que nous concernant les chiffres visiteurs uniques > visites totales et que cela provenait certainement des intégrations iframe. Je suis alors tombé sur cet article :
https://fr.matomo.org/faq/how-to/how-do-i-track-a-website-within-an-iframe/
On peut essayer et voir ce que ça donne sur les prochains jours.
> Ajoute le bout de code recommandé par Matomo pour une bonne prise en compte des iframe

- source/contexts/MatomoContext.tsx
- source/sites/publicodes/entry.js
- webpack.prod.js
Je teste ici en ajoutant le dsn dans les variables d'environnement
A noter :
- La variable d'environnement SENTRY_DSN n'est pas détectée automatiquement (nécessaire de définir l'option dans `init`)
- Après qques tests, il semble que nous ne recevons pas les évènements Sentry depuis localhost **même sans désactivation à la main via l'option 'enabled'**
- Il ne semble pas possible de désactiver l'email depuis les options de la fenêtre de dialogue Sentry **[doc ici]**.(https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/user-feedback/#customizing-the-widget)
> Migration Sentry Beta

- source/components/conversation/Question.tsx
La valeur du `select` n'était pas prise en compte
> Fix bug select in conversation

- source/components/Feedback/NorthstarBanner.tsx
Petit fix, ça cassait en local et en démo
> toString dans NorthStar casse en local et démo

- source/components/ScoreExplanation.tsx
- source/locales/ui/ui-en-us.yaml
- source/locales/ui/ui-fr.yaml
- source/sites/publicodes/ActionsList.tsx
- source/sites/publicodes/Personas.tsx
- source/sites/publicodes/SimulationMissing.tsx
L'objectif : quand on arrive sur /actions, la liste des actions est présente sur la page. Pour le SEO surtout. 
- Popup d'explication du score non pertinente sur /actions
- L'avertissement "débloquage parcours action" ni le tuto ne doivent bloquer l'affichage de la liste des actions, pour quelles soient lisibles directement sur /actions par un moteur de recherche
- mise en retrait des personas, une fonctionnalité qui n'est pas grand publique, dans un petit lien
- réduction de la taille des textes de l'avertissement "débloquage"
- changment d'emoji pour un cadenas plutôt qu'un sablier
- simplification visuelle de l'avertissement pour laisser de la place aux actions notamment
> Affichage permanent des actions sur /actions

- source/locales/blog/fr/mobilite.md
- source/sites/publicodes/pages/BlogData.tsx
- Erreur de date dans une entrée de blog
- Images manquantes dans l'article sur MIT
> blog fixes

- netlify/edge-functions/geolocation.ts
- source/components/localisation/useLocalisation.ts
Corrige le problème ayant apparu récemment : la requête de géolocalisation échouait, ce qui faisait que la bannière d'erreur était systématiquement affichée.
> Mauvaise URL d'accès à l'edge function netlify de geolocalisation

- source/components/utils/Meta.tsx
- source/locales/ui/ui-en-us.yaml
- source/locales/ui/ui-fr.yaml
- source/sites/publicodes/Simulateur.tsx
Le titre de page était `undefined` à la dernière étape avant d'accéder à ses résultats :
> Corrige le titre de page `undefined` à l'étape Résultats

- cypress/e2e/test-completion/url-redirection.cy.js
- source/locales/pages/fr/CGU.md
- source/locales/pages/fr/about.md
- source/locales/pages/fr/privacy.md
Le service juridique a proposé des modifs sur les documents juridiques de NGC : 
- pour les CGU : petites modifs de forme et ajout de quelques phrases de précisions
- pour la politique de confidentialité : mention à Plausible retirée comme on ne va pas l'utiliser ; simplification de la page
- pour les Mentions légales : ajout d'un paragraphe sur la sécurité, réorganisation de la page, petites modifs de formes et quelques phrases de précisions
Commentaire du service juridique sur la politique de confidentialité : "C'est une MAJ. La page actuelle mentionne plein de données qui ne sont pas des données à caractère personnel. J'ai raccourci en précisant juste qui est responsable de NGC, qui héberge NGC (avec les infos sur Netlify, entreprise américaine!) et les infos sur les cookies"
Fixes …
> MAJ documents juridiques

- source/sites/publicodes/pages/Blog.tsx
Ajout d'une illustration pour le blog, pour fournir une vignette lors des partages automatique via linkedin par exemple.
Ajoute également un petit alt sur les vignettes des articles.
> blog : add illustration and add alt txt

- source/components/emailing/NewsletterForm.tsx
Nous avons besoin de permettre à ceux n'ayant pas reçu leur email d'inscription contenant leurs liens pour retrouver leur simulation et de partage de se réinscrire afin de le recevoir.
> Commente le code empêchant l'affichage multiple du formulaire de newsletter

- source/actions/actions.ts
- source/components/publicodesUtils.tsx
- source/reducers/rootReducer.ts
- source/sites/publicodes/Action.tsx
- source/sites/publicodes/App.tsx
La redirection se faisait à cause d'une prop manquante dans `Action.tsx` qui déclenchait ce `useEffect` dans `Conversation.tsx` :
```
useEffect(() => {
// This hook lets the user click on the "next" button. Without it, the conversation
// switches to the next question as soon as an answer is provided.
// It introduces a state
// It is important to test for "previousSimulation" : if it exists, it's not loaded yet.
// Then currentQuestion could be the wrong one, already answered,
// don't put it as the unfoldedStep
if (
currentQuestion &&
!previousSimulation &&
currentQuestion !== unfoldedStep
) {
goToQuestionOrNavigate({
question: currentQuestion,
simulateurRootURL: simulateurRootRuleURL,
focusedCategory,
// NOTE(@EmileRolley): Action card remaining questions are displayed inline, …
```
> 🐛 Passe la prop `isFromActionCard` manquante

- cypress/e2e/test-completion/questions-order.cy.js
- cypress/e2e/test-completion/url-redirection.cy.js
- cypress/e2e/test-completion/utils.js
- scripts/generateSitemap.ts
- source/actions/actions.ts
- source/components/Simulation.tsx
- source/components/conversation/CategoryRespiration.tsx
- source/components/conversation/Conversation.tsx
- source/components/conversation/MosaicInputSuggestions.tsx
- source/components/conversation/RuleInput.tsx
- source/components/conversation/SimulationEnding.tsx
- source/components/conversation/conversationUtils.ts
- source/components/conversation/select/SelectDevices.tsx
- source/components/publicodesUtils.tsx
- source/components/utils/EngineContext.tsx
- source/hooks/useNextQuestion.tsx
- source/reducers/rootReducer.ts
- source/selectors/simulationSelectors.ts
- source/sites/publicodes/ActionConversation.tsx
- source/sites/publicodes/ActionPlus.js
- source/sites/publicodes/BandeauContribuer.js
- source/sites/publicodes/Simulateur.tsx
- source/sites/publicodes/chart/InlineCategoryChart.tsx
- source/sites/publicodes/chart/SpecializedVisualisation.tsx
- source/sites/publicodes/tutorial/Tutorial.tsx
- source/utils.ts
Closes #1159 by removing the previous logic added to skip the tutorial and to go to a specific question when coming from an URL with a specific `question` search param.
~~Now, if the test isn't completed, whatever URL is used, the last unanswered question will be displayed. However, if the user answered all questions, it will display the question corresponding to the rule name specified in the `question` parameter.~~
**EDIT: this PR suspend the feature to go to a specific question even if the test is completed. Indeed, this isn't trivial to differentiate the last question answered from a specific question redirection with the `question` search param.**
Adds a new `thématique` search param for each category _respirations_ (e.g. `thématique=transport`) instead of using the first question of …
> Fix: go to specific question only if the test is completed

- index.html
- source/analytics/matomo-events.ts
- source/sites/publicodes/App.tsx
- webpack.dev.js
- webpack.prod.js
La [fonctionnalité de split testing](https://docs.netlify.com/site-deploys/split-testing/) de Netlify [bug sur iframe](https://answers.netlify.com/t/running-split-tests-in-an-iframe-adjust-nf-ab-cookie-settings/28754). Le cookie déposé par Netlify pour identifier la version du site de l'utilisateur n'est pas compatible avec l'iframe. Ce qui fait que la version serveur et client ne match pas toujours (et le client essaie donc de charger des ressources d'une autre branche).
Pour corriger cela on identifie la version iframe (via le paramètre iframe dans l'url) puis on set manuellement le cookie `nf_ab` avec [sameSite=None et secure](https://medium.com/trabe/cookies-and-iframes-f7cca58b3b9e). Enfin on recharge la page afin d'avoir la bonne version qui s'affiche. Cela entraine une perte de …
> A/B/n Testing via Netlify split testing

- source/components/ui/index.css
- source/global.css
- source/sites/publicodes/App.tsx
~~Il semble qu'on a perdu le padding, je ne sais pas pour quelle raison ce n'était plus pris en compte, peut-être un effet de bord Tailwind ?~~
[EDIT] Il semble que ce soit ici : 
https://github.com/incubateur-ademe/nosgestesclimat-site/blob/f4ecfb9575600b1957b6a619f7910e9908575933/source/sites/publicodes/App.tsx#L335-L336
Mais je ne suis pas sur de comprendre l'utilité d'imposer ce padding ?
Je ne vois pas non plus dans le git blâme à quoi sert cet ajout :/
> Fix: padding

- source/sites/publicodes/Actions.tsx
- source/sites/publicodes/Contact.tsx
- source/sites/publicodes/Simulateur.tsx
- source/sites/publicodes/conference/GroupSwitch.tsx
- source/sites/publicodes/pages/GuideGroupe.js
- source/sites/publicodes/pages/MarkdownPage.tsx
- source/sites/publicodes/pages/Stats.js
fix #1204
J'ai utilisé le composant scrollToTop déjà utilisé.
Si il est mal placé, il peut ne pas fonctionner.
> add scrollToTop to several pages

- source/components/AnimatedIllustration.tsx
- source/sites/publicodes/Landing.tsx
#1200 
Ici le poids de l'image en soi n'est pas le problème mais plutôt la manière dont elle était chargée, en lazy loading, et donc avec un délai, ce qui faisait se décaler le contenu de la page vers le bas, ce qui est pénalisé sur le plan du SEO.
> Retire le lazy loading sur l'image de la page d'accueil

- .gitignore
- dist/demo-iframe.html
- dist/demo-iframeSimulation.html
- source/Provider.tsx
- source/components/Footer.tsx
- source/components/IframeResizer.tsx
- source/components/Logo.tsx
- source/components/localisation/Localisation.tsx
- source/components/localisation/LocalisationMessage.tsx
- source/components/localisation/useLocalisation.ts
- source/components/localisation/utils.ts
- source/locales/ui/ui-en-us.yaml
- source/locales/ui/ui-fr.yaml
- source/reducers/rootReducer.ts
- source/sites/publicodes/App.tsx
- source/sites/publicodes/iframe.js
- source/sites/publicodes/iframeSimulation.js
- webpack.common.js
Suite au travail mené dans https://github.com/incubateur-ademe/nosgestesclimat/pull/1872, l'idée ici est de proposer une solution d'intégration du site dans un site intégrateur qui porte la responsabilité d'un modèle régionalisé dans un site "vitrine". 
On peut prendre ici l'exemple de https://nosgestesclimat.ch pour la suisse donc.
En bref, via le script de l'iframe, on a 2 nouvelles options.
L'option "data-localisation" qui permet de fixer la localisation pour charger le modèle voulu. Le bandeau de localisation et la détection auto sont alors désactivés.
L'option "data-only-simulation" qui permet de faire disparaitre le Footer NGC pour mettre en valeur celui du site intégrateur et la disparition de la redirection vers la home NGC via le logo. Un autre élément important, on affiche non …
> Nouvel Iframe de simulation
