source/components/Simulation.tsx, source/components/conversation/Conversation.tsx, source/components/utils/colors.tsx, source/selectors/analyseSelectors.ts, source/sites/publicodes/chart/Value.js
Fixes betagouv/ecolab-data/issues/11
=> Couleur des catégories et classement par catégorie la plus influente

source/components/Simulation.tsx, source/components/conversation/CategoryRespiration.js, source/components/conversation/Conversation.tsx, source/sites/publicodes/Landing.js, source/sites/publicodes/Simulateur.js, source/webpack.common.js
Un écran qui fait une pause et annonce la couleur.
Attention, c'est moche pour l'instant.
=> Respirations entre chaque catégorie

source/components/conversation/AnswerList.tsx, source/components/conversation/Conversation.tsx, source/components/conversation/InputSuggestions.tsx, source/locales/en.yaml, source/sites/publicodes/App.js, source/sites/publicodes/Contribution.js, source/sites/publicodes/Landing.js, source/sites/publicodes/about.md
Quelques améliorations d'interface
Fixes #2
=> Améliorations d'interface

package.json, source/components/ShareButton.js, source/components/conversation/Conversation.tsx, source/components/utils/colors.tsx, source/sites/publicodes/App.js, source/sites/publicodes/Fin.js, source/sites/publicodes/Simulateur.js, source/sites/publicodes/images/ballonGES.svg, yarn.lock
1ère version, brute.
2ème, un peu mieux
=> Ecran de fin de simulation

CONTRIBUTING.md, source/Provider.tsx, source/RulesProvider.js, source/sites/publicodes/App.js, source/sites/publicodes/Fin.js, source/webpack.common.js
=> Branches data

source/sites/publicodes/App.js
Je n'avais pas vu l'erreur, car en local on charger les -data locales 😐
=> :bug: Erreur logique JS qui plante le site

source/sites/publicodes/Simulateur.js
=> Intégration du score de simulation dans l'événement fin de sim

source/sites/mon-entreprise.fr/pages/Documentation/RulesList.tsx, source/sites/publicodes/Contribution.js, source/sites/publicodes/FAQ.md
Pour qu'elle évolue de façon contributive avec des PRs et un historique public.
Closes #170
=> Passage de la FAQ d'une issue à un fichier

source/sites/publicodes/About.js, source/sites/publicodes/about.md
=> Mise à jour de la page à propos

source/RulesProvider.js, source/sites/publicodes/ActionPlus.js, source/sites/publicodes/Actions.js, source/sites/publicodes/ListeActionPlus.js
Pour google, les rédacteurs et les curieux
Fixes #131
=> Liste des fiches élaborées

source/sites/publicodes/Action.js, source/sites/publicodes/Actions.js
=> Actions sans chiffres

source/sites/publicodes/App.js, source/sites/publicodes/VersionBeta.js
Fixes #141
ça te va comme ça Martin ?
je l'ai mis en bas, car en haut sans couleur de fond c'est très moche, et on a moins besoin de retours maintenant.
=> Finie la beta !

package.json, source/components/utils/markdown.tsx, yarn.lock
Impossible de le faire marcher, j'ai posé la question ici https://github.com/remarkjs/react-markdown/issues/337#issuecomment-738012113
edit : voilà c'est bon, vallait faire une partie du boulot à la main
=> Ajout des notes de bas de page au markdown

source/components/utils/markdown.tsx, source/sites/publicodes/Actions.js, source/sites/publicodes/ListeActionPlus.js
Nous sommes en environnement controlé.
Notamment pour utiliser les balises summary.
=> Autorisation du html dans le markdown + encart visuel pour les actions

source/components/publicodesUtils.js, source/sites/publicodes/ActionPlus.js, source/sites/publicodes/ListeActionPlus.js
=> Fix fiches plus

source/sites/publicodes/iframe.js
=> Changement d'URL de l'iframe

source/components/conversation/Input.tsx
Et je ne pige pas à quoi il sert., le debounce servant justement pour ne pas abuser en ré-calculs  ?
Fixes #178
=> :bug: Cette vérif posait problème si saisie de la valeur par défaut

source/sites/publicodes/images/ecolab-climat-dessin.svg
=> Illustration train

source/components/conversation/Aide.tsx, source/components/conversation/Conversation.tsx, source/components/conversation/Explicable.tsx, source/components/conversation/mosaicQuestions.ts
> Un commit que j'avais oublié de pousser dans la PR mergée il y a 10 minutes.
=> Bulles d'aide pour les questions mosaïque

source/components/conversation/Conversation.tsx, source/sites/publicodes/App.tsx
Fixes #213 
Fixes #212
Fixes #211
Fixes #210
Cette PR embarque aussi un fix #175 
Merci @hmartinez69 :)
=> Bug popup description

source/components/SessionBar.tsx, source/components/conversation/AnswerList.tsx
Fixes datagir/nosgestesclimat#985
Fixes datagir/nosgestesclimat#981
=> Plus de bouton "Terminer", remplacé par "Recommencer"

source/components/conversation/Input.tsx
=> 🐛 Résolution du bug d'unité avec une implé bien plus propre de <Input />

source/sites/publicodes/HumanWeight.js, source/sites/publicodes/chart/Value.js, source/sites/publicodes/conference/CategoryStats.tsx, source/sites/publicodes/conference/Conference.tsx, source/sites/publicodes/conference/Stats.tsx, source/sites/publicodes/conference/UserList.tsx
=> Conf : meilleurs graphiques et résolutions de bugs

source/sites/publicodes/about.md
Je pense qu'ils sont pas pertinents vu le reste du contenu de cette page, et puis les liens servent justement à ça. 🙂
Si ça vous semble vraiment essentiel @martinregner @Benjamin-Boisserie-ABC on peut créer une nouvelle page pour raconter le contexte
=> suppression des paragraphes de prez ABC et betagouv

source/components/conversation/mosaicQuestions.ts
Voir https://github.com/datagir/nosgestesclimat/pull/975
Démo https://deploy-preview-260--nosgestesclimat.netlify.app/simulateur/divers/électroménager/?PR=975
=> Ajout de la mosaïque électroménager

source/sites/publicodes/CarbonImpact.js, source/sites/publicodes/conference/Conference.tsx
=> Quelques améliorations de /conf

source/sites/publicodes/Action.js
=> :bug: affichage des actions plus

source/components/conversation/RuleInput.tsx, source/sites/publicodes/DefaultFootprint.tsx, source/sites/publicodes/Fin.js, source/sites/publicodes/conference/Stats.tsx
=> Utilisation d'une valeur par défaut français calculée

source/components/conversation/Conversation.tsx, source/components/publicodesUtils.js, source/reducers/rootReducer.ts
J'ai pas eu le temps de finir cette PR avant de partir en vacances :crying_cat_face: 
Fixes #269 
Fixes datagir/nosgestesclimat#1022
Fixes datagir/nosgestesclimat#1122
Fixes datagir/nosgestesclimat#1059
=> Tentative de réintroduction du bouton retour tant demandé

source/components/conversation/Conversation.tsx, source/components/conversation/RuleInput.tsx, source/components/conversation/mosaicQuestions.ts, source/components/conversation/select/NumberedMosaic.tsx, source/components/conversation/select/SelectDevices.tsx, source/components/conversation/select/SelectWeeklyDiet.js, source/sites/publicodes/personas.yaml
Pour tester : https://deploy-preview-319--nosgestesclimat.netlify.app/simulateur/divers/textile?PR=1125
=> Mosaique textile

source/sites/publicodes/Fin.js
=> Arrondis fin

source/sites/publicodes/Fin.js
=> Bug bouton partage

source/sites/publicodes/conference/CategoryStats.tsx, source/sites/publicodes/conference/Conference.tsx, source/sites/publicodes/conference/ConferenceBar.tsx, source/sites/publicodes/conference/Stats.tsx, source/sites/publicodes/conference/UserList.tsx, source/sites/publicodes/conference/utils.tsx
=> Conf max score

.gitignore, dist/demo-iframe.html, source/Provider.tsx, source/components/conversation/select/NumberedMosaic.tsx, source/components/conversation/select/SelectDevices.tsx, source/components/utils/IframeOptionsProvider.tsx, source/sites/publicodes/Fin.js, source/sites/publicodes/Logo.js, source/sites/publicodes/iframe.js
Toutes les options d'intégration sont [dispo ici](https://github.com/datagir/nosgestesclimat-site/blob/0bc98dcf74859b3056f1274b0aa8401fa61f4cb6/dist/demo-iframe.html)
Exemple avec des options fantaisistes. 
Closes #329
=> Chargement d'un logo partenaire via l'iframe

source/components/conversation/select/NumberedMosaic.tsx, source/sites/publicodes/IframeDataShareModal.tsx, source/sites/publicodes/Logo.js, source/sites/publicodes/SubCategoryBar.tsx, source/sites/publicodes/conference/UserList.tsx
Fixes datagir/nosgestesclimat/issues/1178
Fixes https://github.com/datagir/nosgestesclimat/issues/1181
=> Bug fin sept 21

source/sites/publicodes/Contribution.js
On favorise un retour direct sur github, et on réserve le retour en un
clic aux bugs critiques.
Fixes #374
=> Mise en retrait du formulaire de retour libre

source/components/conversation/Conversation.tsx, source/components/conversation/mosaicQuestions.ts, source/components/conversation/select/NumberedMosaic.tsx, source/components/conversation/select/SelectDevices.tsx, source/components/ui/Card.css, source/components/ui/Checkbox/index.css, source/components/ui/Checkbox/index.tsx, source/components/ui/reset.css, source/sites/publicodes/ActionVignette.js
=> Mosaique sans défauts

source/sites/publicodes/Personas.tsx, source/sites/publicodes/personas.yaml
Profil "mère seule avec 2 enfants"
=> Compléments profils

PERSONNALISATION.md, README.md, source/sites/publicodes/diffuser.md
=> Nouveau guide de personnalisation de NGC

source/components/conversation/AnswerList.tsx, source/components/conversation/mosaicQuestions.ts, source/components/publicodesUtils.js, source/sites/publicodes/personaSteps.yaml, source/sites/publicodes/personas.yaml, source/storage/persistSimulation.ts
Modification coté site pour la PR https://github.com/datagir/nosgestesclimat/pull/1280.
=> Mosaique chauffage

source/sites/publicodes/ActionVignette.js, source/sites/publicodes/HumanWeight.js, source/sites/publicodes/personas.yaml
- Ximun utilise surtout le bus
- Jessica devient réellement (ou presque) végétarienne
- :bug: humanWeight ne renvoyait pas la valeur avec un signe
- Gestion des actions qui augmentent l'impact
- Gestion du signe de l'action pour les % aussi
=> amélioration action végé

source/sites/publicodes/ActionVignette.js, source/sites/publicodes/HumanWeight.js
=> :bug: Mauvaise algo d'affichage du sign moins

source/sites/publicodes/AllActions.tsx
- Segmentation des actions par poids
- Style de la segmentation des actions
=> Segmentation des actions par ordre de grandeur d'empreinte

index.html, source/sites/publicodes/Tutorial.tsx, source/sites/publicodes/chart/Bar.js, source/sites/publicodes/chart/Value.js, source/sites/publicodes/chart/index.js, webpack.common.js
On a changé le chemin dans webpack.common.js
=> :bug: Logo et illustration manquantes

source/sites/publicodes/Fin.js, source/sites/publicodes/chart/Bar.js, source/sites/publicodes/chart/index.js
- Réparation de l'animation du graphe
- La page de fin a besoin de noAnimation
=> animation graphique

source/components/SessionBar.tsx, source/components/conversation/AnswerList.tsx, source/sites/publicodes/Landing.js, source/sites/publicodes/Profil.tsx
Dernier commit seulement est intéressant. À rebaser une fois la PR mosaique chauffage mergée. 
Reste un mauvais affichage de bois . présent. À investiguer.
Fixes  #410 (pas complètement mais j'assume)
=> Profil récursif

source/components/conversation/Conversation.tsx, source/components/emoji.js, source/images/270A.svg, source/sites/publicodes/AllActions.tsx, source/sites/publicodes/Tutorial.tsx
Je corrige ici les derniers bugs relevés. 
:bug: Affichage des emojis, pas besoin de styler le p entier
Fixes #427
=> Bugs de décembre

source/sites/publicodes/Tutorial.tsx
Aurait du être repéré par un linter, index étant indéfini, il faudra
qu'on réfléchisse à l'enforcer, même si c'est le 1er bug ainsi provoqué
depuis le début du projet
=> :bug: Code réordonné que partiellement

source/sites/publicodes/Fin.js
Suppression du "null" ajouté par erreur ?
=> Proposition trackers sans bug

source/sites/publicodes/ActionConversation.tsx, source/sites/publicodes/ActionVignette.js, source/sites/publicodes/Simulateur.js, source/sites/publicodes/questionConfig.js
Les questions pourtant en liste noire apparaissent dans la conversation des actions
=> Ajout liste noire pour les actions

source/components/SearchButton.tsx, source/components/SessionBar.tsx, source/components/Simulation.tsx, source/components/conversation/CategoryRespiration.js, source/components/conversation/Conversation.tsx, source/components/conversation/Explicable.tsx, source/components/conversation/InputSuggestions.tsx, source/components/conversation/Question.tsx, source/components/conversation/QuestionFinder.tsx, source/components/conversation/QuestionFinder.worker.ts, source/components/conversation/estimate/EditableRow.js, source/components/conversation/estimate/KmForm.js, source/components/conversation/estimate/KmHelp.tsx, source/components/conversation/select/SelectDevices.tsx, source/components/highlightMatches.tsx, source/components/ui/Checkbox/index.tsx, source/components/ui/Toggle.css, source/components/ui/index.css, source/components/utils/useKeyPress.ts, source/images/1F50D.svg, source/images/274C.svg, source/sites/publicodes/Tutorial.tsx
Celui de la question capture le enter sur les radio. Ils capturent la navigation et le enter quand ils sont sur chaque radio.
Traite une partie de #442
=> navigation clavier

index.html, source/components/SessionBar.tsx, source/components/ShareButton.js, source/components/conversation/Conversation.tsx, source/components/conversation/Input.tsx, source/components/conversation/InputSuggestions.tsx, source/components/conversation/select/NumberedMosaic.tsx, source/components/conversation/select/SelectDevices.tsx, source/components/utils/Meta.tsx, source/images/LogoADEME.js, source/sites/publicodes/Action.js, source/sites/publicodes/ActionPlus.js, source/sites/publicodes/ActionVignette.js, source/sites/publicodes/App.tsx, source/sites/publicodes/CarbonImpact.js, source/sites/publicodes/CategoryFilters.tsx, source/sites/publicodes/Fin.js, source/sites/publicodes/Landing.js, source/sites/publicodes/Navigation.tsx, source/sites/publicodes/Profil.tsx, source/sites/publicodes/Simulateur.js, source/sites/publicodes/SkipLinks.tsx, source/sites/publicodes/chart/Bar.js, source/sites/publicodes/images/Marianne.svg, source/sites/publicodes/images/ballonGES.svg, source/sites/publicodes/images/ecolab-climat-dessin.svg
C'est fait, sauf erreurs, oublis, tous les points sont respectés, sauf le "niveau accessibilité sur toutes les pages", en attendant l'audit. 
J'ai enlevé un check "? unfoldedStep" qui me semblait servir à rien
=> Accessibilité v3 & Filtre par catégorie de la conversation

source/components/SessionBar.tsx, source/images/26D4.svg, source/sites/publicodes/AllActions.tsx, source/sites/publicodes/personaSteps.yaml, source/sites/publicodes/personas.yaml
https://voiture-electrique--nosgestesclimat.netlify.app/?PR=1351
datagir/nosgestesclimat#1351
=> Renaissance des actions négatives

source/sites/publicodes/Guide.js
Pour compléter https://github.com/datagir/nosgestesclimat/pull/1353
=> Suite fiches guide

source/components/conversation/mosaicQuestions.ts, source/sites/publicodes/conference/DataWarning.tsx, source/sites/publicodes/conference/NoTestMessage.tsx, source/sites/publicodes/conference/Stats.tsx, source/sites/publicodes/personas.yaml
Pour compléter et répondre aux retours de l'atelier réalisé pendant la convention (https://github.com/datagir/nosgestesclimat/pull/1358)
Dans cette PR pour le moment:
- Les simulations dont l'avancement est inférieur à 10% ne s'affichent pas dans la page de visualisation
- Les utilisateurs qui arrivent sur la page du mode groupe sans avoir fait de simulation n'arrivent pas sur l'écran de visualisation directement mais sur un message qui les rédirige vers le test
C'est peut-être l'occasion de résoudre les bugs remontés ici #495 @laem (si c'est peu couteux en temps)
=> Retours suite atelier convention côté site

dist/demo-iframe.html, source/sites/publicodes/fin/IframeDataShareModal.tsx
- Placement de la pop up de partage de partage
- Amélioration du texte de partage des données iframe
- Amélioration légère du style du modal de partage de données
- Ajout de l'option de partage à la démo de l'iframe
Remplace #509
=> popup partage données iframe

source/sites/publicodes/fin/IframeDataShareModal.tsx
par dessus le contenu.
En relation avec l'issues que j'ai ouvert précédemment #508
=> Placement de la pop up de partage de partage

source/components/ShareButton.tsx, source/components/conversation/Conversation.tsx, source/reducers/rootReducer.ts, source/sites/publicodes/ActionVignette.js, source/sites/publicodes/Landing.js, source/sites/publicodes/Simulateur.js, source/sites/publicodes/fin/index.tsx
L'objectif de cette PR est de mieux cartographier le parcours utilisateur via des évènements matomo.
Lié à #443 & #517
=> Amélioration des indicateurs du tracking

source/sites/publicodes/fin/index.tsx
L'idée est d'avoir une idée du nombre de swipe par simulation.
=> Ajout tracker swipe page de fin

source/components/conversation/Question.tsx
=> MAJ css point info réponse question

source/components/conversation/Conversation.tsx, source/sites/publicodes/conference/ContextConversation.tsx, source/sites/publicodes/conference/FilterBar.tsx, source/sites/publicodes/conference/Stats.tsx, source/sites/publicodes/conference/Survey.tsx
On peut désormais filtrer les résultats lors d'un sondage avec contexte sur la page de visualisation.
J'ai l'impression que le code est un peu complexifié avec cette fonctionnalité .. et le fait que les réponses dans la situation soient entre guillemets a posé problème..
@laem je peux te laisser faire une petite review ?
=> Amélioration analyse sondage contexte

source/components/conversation/Conversation.tsx, source/components/conversation/InputSuggestions.tsx, source/components/conversation/MosaicInputSuggestions.tsx, source/components/conversation/RuleInput.tsx, source/components/conversation/mosaicQuestions.ts, source/components/conversation/select/NumberedMosaic.tsx, source/components/conversation/select/SelectDevices.tsx, source/components/ui/Button/button.css, source/components/utils/useNextQuestion.tsx, source/sites/publicodes/Personas.tsx, source/sites/publicodes/questionConfig.js
Lié à https://github.com/datagir/nosgestesclimat/pull/1419
=> Nouvelle mosaïque boissons chaudes & ajout suggestions mosaïques

source/components/conversation/select/NumberedMosaic.tsx, source/components/conversation/select/SelectDevices.tsx, source/components/ui/Checkbox/index.tsx
Pour corriger #575 
Démo : https://fix-label-mosaic-selectdevice--nosgestesclimat.netlify.app
=> Fix label checkbox

source/components/conversation/mosaicQuestions.ts
Lié à https://github.com/datagir/nosgestesclimat/pull/1415
=> Ajout mosaïque gestes zéro déchets

source/components/conversation/Conversation.tsx, source/components/stats/StatsContent.js, source/components/stats/content/DurationFigures.js, source/components/stats/content/KmFigures.js, source/components/stats/content/chart/CustomTooltip.js, source/components/stats/content/histogram/CustomTooltip.js
=> Amélioration des statistiques

source/sites/publicodes/conference/GroupSwitch.tsx, source/sites/publicodes/conference/Survey.tsx
Comme discuté avec @Clem-mrtn, la mention beta n'est plus vraiment pertinente : certains utilisateurs peuvent manquer de confiance alors que le mode conférence/sondage fonctionne bien (plus de 150 sondages avec aux moins 10 réponses par exemple)
=> Le mode groupe n'est plus une version beta

source/components/stats/utils/FancySelect.js
=> :bug: Choix d'options de stats transparent sur chrome

source/components/utils/EngineContext.tsx, source/utils.ts
Suite à une évolution de publicodes. CF la doc du commit
=> :bug: Chargement des personas et des anciennes simulations bugguées

source/components/conversation/Conversation.tsx, source/components/conversation/Input.tsx, source/components/conversation/InputEstimation.tsx, source/components/conversation/estimate/EditableRow.js, source/components/conversation/estimate/KmForm.js, source/components/conversation/estimate/KmHelp.tsx, source/components/conversation/estimate/ReadOnlyRow.js, source/components/conversation/select/NumberedMosaic.tsx, source/sites/publicodes/conference/FilterBar.tsx
Démo : https://format-input-number--nosgestesclimat.netlify.app/?PR=1454
=> Formattage input nombres

source/sites/publicodes/HumanWeight.js
=> fix(ui): all result values are now accurate to one decimal point

source/components/Modal.tsx, source/sites/publicodes/Landing.js, source/sites/publicodes/SurveyModal.js
=> Ajout enquête utilisateurs

index.html, package.json, source/components/Simulation.tsx, source/sites/publicodes/Action.js, source/sites/publicodes/ActionConversation.tsx, source/sites/publicodes/Simulateur.js, webpack.common.js, webpack.prod.js, yarn.lock
- Composants chargés inutilement, repéré via le CSS chargé
- Option CSS sourceMap à gérer par "devtools"
=> petites optimisations

source/selectors/storageSelectors.ts, source/sites/publicodes/App.tsx
- Ordre dans les imports de App
- La vérification des règles se fait maintenant dans EngineContext
=> bug données

source/sites/publicodes/DefaultFootprint.tsx
La PR précédente mergée en hâte, trop.
=> bug conf with engine 2

source/RulesProvider.js, source/components/ProgressCircle.tsx, source/components/conversation/AnswerList.tsx
Voir https://github.com/datagir/nosgestesclimat-site/issues/649 pour faire mieux
=> F5 /profil -> bug cercle d'avancement, mitigation

source/components/conversation/MosaicInputSuggestions.tsx, source/components/conversation/select/SelectDevices.tsx
Une suggestion "Aucun" sera automatiquement proposée pour les mosaïques de sélection afin de ne pas bloquer l'utilisateur qui ne dispose pas du bouton lorsqu'il ne veut rien cocher
@laem j'ai l'impression que j'ai des erreurs du typage dans ma proposition ..
=> Suggestion auto "aucun"

.gitmodules, README.md, source/RulesProvider.js, source/components/useFetchDocumentation.ts, source/sites/publicodes/Personas.tsx
Add `nosgestesclimat` as [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules).
=> feat(build)!: add nogestesclimat as a submodule

.gitmodules
@EmileRolley @Clemog ça me semble mieux non  ?
=> Passage du submdule nosgestesclimat en SSH

source/sites/publicodes/App.tsx, source/sites/publicodes/Navigation.tsx
Debugging épique avec @emilerolley :D
=> :bug: Le hot reloading avait disparu.

source/sites/publicodes/pages/Documentation.tsx
Attention @EmileRolley, erreur classique, et j'avoue que c'est très tentant de la faire :D
=> :bug: Pas de hook après des return dans un composant

source/locales/ui/ui-en-us.yaml
Fixes https://github.com/datagir/nosgestesclimat/issues/1575
=> fix(t9n): 'I do not know' -> 'I don't know'

source/components/LangSwitcher.tsx, source/components/Logo.tsx, source/components/SessionBar.tsx, source/components/TranslationAlertBanner.tsx, source/sites/publicodes/App.tsx, source/sites/publicodes/Landing.tsx
Partially fixes #723 by providing a more intuitive UI for the language switcher. Moreover, the button is more accessible from the landing page.
https://user-images.githubusercontent.com/44124798/202168217-a57ee29c-c7ee-49b7-8626-50dede45f0ca.mp4
=> feat(ui): new LangSwitcher design 

source/components/utils/Meta.tsx, source/sites/publicodes/LandingExplanations.tsx, source/sites/publicodes/pages/MarkdownPage.tsx
@EmileRolley good for you ? 
(I didn't test on the preview yet)
=> Make MarkdownPage Meta optional; fix #742 no desc meta on landing

source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-es.yaml, source/locales/ui/ui-fr.yaml, source/locales/ui/ui-it.yaml, source/sites/publicodes/conference/Instructions.tsx, source/sites/publicodes/conference/LoadingButton.tsx, source/sites/publicodes/conference/SurveyBar.tsx, source/sites/publicodes/conference/useYjs.tsx
J'ai coché les cases de #707 que je pense avoir résolues ici. 
Je merge rapidement car ce sont essentiellement des bugs ou des réorganisation de textes consensuelles, mais ça n'empêche d'itérer bien sûr.
=> Résolution de bugs du sondage

index.html, source/locales/i18n.ts, source/sites/publicodes/App.tsx
- Commentaire manquant
- Nouvelle constante globale pour forcer la langue du site
- Remove unused default lang param
=> Google nous voit en anglais, tentative de résolution

source/components/stats/StatsContent.js, source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml
Add a wrapper around `UseQueryResult` to avoid white page when only one request fails.
=> fix(stats): more granularity to stats rendering

scripts/fetch-releases.js, source/components/NewsBanner.tsx, source/data/last-release.json, source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml, source/pages/News.tsx
- Old variables for releases
- Qu'on n'affiche plus "fake release" sur la home
Fixes  #636
=> fake release bug

source/components/emoji.tsx, source/sites/publicodes/LandingExplanations.tsx
Maxcdn a disparu, nos emojis s'affichent donc mal ou pas du tout :/
On voit le problème d'une telle dépendance, alors que les emojis sont en
grande majorité bien gérés nativement.
=> Notre CDN d'emojis est down

source/components/useFetchDocumentation.ts
PR jumelle de https://github.com/datagir/nosgestesclimat/pull/1638
=> Suite services sociétaux côté site

scripts/generateSitemap.js, scripts/prepare.js, source/components/useBranchData.ts, source/locales/faq/FAQ-fr.yaml
=> Passage de ecolab-data.netlify.app à data.nosgestesclimat.fr pour master

source/components/useBranchData.ts
Rien ne grave, mais l'ancienne PR ne servait pas à grand chose.
=> :bug: l'URL du modèle n'était pas changée :/

source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml, source/sites/publicodes/conference/DataWarning.tsx, source/sites/publicodes/conference/Instructions.tsx, source/sites/publicodes/conference/NamingBlock.tsx, source/sites/publicodes/conference/Stats.tsx, source/sites/publicodes/conference/Survey.tsx, source/sites/publicodes/conference/SurveyBar.tsx
Fixes #823
fixes #819
fixes #822
=> Diverses améliorations du parcours groupe

source/sites/publicodes/chart/DetailedBarChartIcon.tsx, source/sites/publicodes/chart/InlineCategoryChart.tsx, source/sites/publicodes/chart/SubCategoriesChart.tsx, source/sites/publicodes/chart/index.js
Fixes #803 
C'est bien mieux quand ça marche ! Ça rend le test bien plus interactif. 
J'ai introduit un nouvel icône, suffisamment discret pour ne pas sauter aux yeux et perturber les CTA du test.
=> Bug graphique de simu & graphique en barres

source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml, source/sites/publicodes/Navigation.tsx
Updates the UI's translation in en-US and removes the overflow of the navbar.
=> Fix UI trad and navbar overflow

source/components/localisation/Localisation.tsx, source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml, source/sites/publicodes/Tutorial.tsx
=> Typo méthane dans le tutoriel

source/components/SessionBar.tsx, source/sites/publicodes/Landing.tsx, source/sites/publicodes/ScoreBar.tsx
- Retour en arrière sur 9a3e8c817e03f9432820ca7e4b2d30a5f0878bfb
- Spécification plus complète de media query pour cibler les iphone 5S
=> fix css nav bar media quries

source/components/localisation/utils.ts
=> fix: check if currentLang is in regionParams

source/RulesProvider.tsx, source/components/localisation/RegionGrid.tsx, source/components/localisation/useCurrentRegionCode.ts, source/components/localisation/utils.ts
* The current region flag is colored in the profil section.
* New util function `getCurrentRegionCode`.
=> feat(ui): colorize selected country flag in the profil

source/components/localisation/Localisation.tsx, source/components/localisation/RegionGrid.tsx, source/components/localisation/RegionModelAuthors.tsx, source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml
Display new `authors` region params:
=> feat(i18n): display region model authors

package.json, source/sites/publicodes/App.tsx, source/sites/publicodes/entry.js, yarn.lock
Closes #941
The bundle size goes from 5.83 MB (without Sentry) to 6.23 MB (with Sentry).
=> feat: setup Sentry

source/components/conversation/amortissement-avion/FieldTravelDuration.tsx, source/components/conversation/amortissement-avion/Form.tsx, source/reducers/rootReducer.ts, source/storage/persistSimulation.ts
=> Fix double clé storedAmortissement dans le store redux

source/components/LandingLayout.tsx, source/components/PartnerBanner.tsx, source/components/utils/IframeOptionsProvider.tsx, source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml, source/sites/publicodes/Landing.tsx
=> Change le label du CTA de la Landing si une simulation est déjà commencée ou terminée

scripts/fetch-releases.js, source/pages/News.tsx
=> Le téléchargement des releases au build doit marcher ou casser le build

source/components/useBranchData.ts
L'app casse en prod, notamment sur les animaux domestiques, on tente un fix
=> Fix bugs suite merge enquête

cypress/e2e/test-completion/questions-order.cy.js, source/components/conversation/Conversation.tsx
Une regression est apparue au moment du refacto analytics. J'ai procédé à un fix potentiellement temporaire car je ne suis pas certain de maitriser tous les effets de bords potentiels qu'il pourrait entrainer.
J'ajoute également un test e2e qui nous protègera à l'avenir de ce type de régression.
=> 🐛 Corrige le bug d'ordre de questions

package.json, source/contexts/Tracker.ts, yarn.lock
La dépendance non utilisée nous a créé une PR automatique de MAJ, je
prefère éviter. On utilisera l'historique si besoin pour aller récupérer
les bouts de code pertinents.
Fixes  #1066
=> Suppression de posthog

source/sites/publicodes/fin/index.tsx, source/sites/publicodes/pages/QuickDocumentationPage.tsx, source/sites/publicodes/tutorial/ClimateWarming.tsx, source/sites/publicodes/tutorial/Tutorial.tsx
Le cache ne fonctionnait plus, et faisait une dépendance externe.
Au profit de l'idée datagir/ogimager.
=> Nouveau système de génération d'images meta pour page de fin

source/actions/actions.ts, source/components/Feedback/Northstar.tsx, source/components/Feedback/NorthstarBanner.tsx, source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml, source/reducers/rootReducer.ts, source/selectors/storageSelectors.ts
Quelques changements dans les types et le state.
J'ai ajouté les trad.
J'ai ajouté un nouvel état initial, pour mieux gérer l'ensemble :
- no_display : état inital, bannière non affichée, data pas encore envoyé au serveur
- display : lorsque la bannière est affiché, on envoie cette information au serveur et on maj le state avec cette valeur
- refuse : utilisateur a fermé la bannière
- 0|1|2|3 : les valeurs des notes envoyées au serveur
Les états display et no_display permettent d'afficher la bannière.
=> set northstar score to a fixed range or two strings

source/sites/publicodes/conference/GroupStats.tsx
Je sollicite @EmileRolley pou @bjlaa pour une séance de pair programming pour clean ces fichiers de contexte et passer en ts (ça me permettrait d'être plus à l'aise je pense, je vois du rouge partout ..)
=> el.context semble pouvoir être non défini

source/components/stats/StatsContent.js, source/components/stats/content/Chart.tsx, source/components/stats/content/DurationFigures.js, source/components/stats/content/Evolution.js, source/components/stats/content/Sources.js, source/components/stats/content/chart/Search.js, source/components/stats/matomo.js, source/components/stats/utils/Section.js
=> Ajoute certaines des statistiques manquantes

source/sites/publicodes/Contribution.js
fix #1161 
J'ai ajouté un système pour aller à la question et déplier la réponse.
En plus, lorsqu'on clique sur une question, ça change l'ancre de l'url, pour pouvoir copier/coller facilement.
=> faq : add a system for anchors

source/components/emailing/NewsletterForm.tsx, source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml
@bjlaa je veux bien ton avis, je ne sais pas si c'est la bonne approche
Il faudra surement penser à relancer la trad au passage
=> Newsletter form breaks local dev

source/components/conversation/AnswerList.tsx
Gros bug : https://sentry.incubateur.net/organizations/betagouv/issues/52466/?project=100&query=is%3Aunresolved&referrer=issue-stream
=> Fix wrong import

source/components/publicodesUtils.tsx
Visiter la page questions entrainait une ErrorBoundary
=> Répare la page /questions

source/locales/pages/fr/petrogazLanding.md, source/locales/pages/it/landing.md, source/sites/publicodes/tutorial/Target.tsx
Toute petite pr pour modifier un lien dans 3 fichiers.
=> replace datagir blog link with a local one

source/locales/pages/en-us/landing.md, source/locales/pages/fr/landing.md
- "bientôt un million de tests" --> "plus d'un million de tests"
- typo gaz à effet de serre
- MAJ lien vers le blog NGC pour l'article budget
=> MAJ landing

source/reducers/rootReducer.ts
Ce [commentaire](https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1108/files#r1261494762) était passé à la trappe lors de la review de ma PR. Je corrige ici le problème soulevé par @EmileRolley
=> Retire code dupliqué

source/reducers/rootReducer.ts
Reverts incubateur-ademe/nosgestesclimat-site#1239
=> Revert "Retire code dupliqué"

source/reducers/rootReducer.ts
Correctly fix https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1239
=> fix: remove correctly the rootReducer code duplicate

source/locales/faq/FAQ-en-us.yaml, source/locales/faq/FAQ-fr.yaml
- MAJ question "qu'est-ce que l'empreinte carbone"
- Ajout question "comment la mesure-t-on ?"
=> MAJ FAQ pour le tutoriel

source/components/publicodesUtils.tsx, source/components/utils/EngineContext.tsx, source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml, source/pages/groupe-dashboard/hooks/useGetGroupStats.ts, source/sites/publicodes/Personas.tsx, source/sites/publicodes/Simulateur.tsx
=> Fix bug setting personas

source/images/model/divers . loisirs.svg
Lié à https://github.com/incubateur-ademe/nosgestesclimat/pull/1999
=> Ajout emoji loisirs

source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml, source/pages/groupe-dashboard/components/FeedbackBlock.tsx
Suite à #1252, je remarque qu'il manquait les traductions (cf https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1252#issuecomment-1649282487)
@florianpanchout, ça se fait via `yarn check:ui` puis `yarn translate:ui`:)
=> feat: update translations

source/sites/publicodes/ActionsList.tsx
Il était possible d'interagir avec l'écran actions sans avoir passé le test, ce qui amenait des comportements non voulus et problématiques.
=> 🐛 Désactive les actions quand l'utilisateur n'a pas encore passé le test

source/components/Feedback/NorthstarBanner.tsx
Réduit le nombre d'actions à cocher + ajoute scroll auto
=> Facilite l'affichage de la bannière northstar 2

source/components/SessionBar.tsx, source/pages/groupe-dashboard/components/Badge.tsx, source/pages/groupe-dashboard/components/PointsFortsFaibles.tsx, source/pages/groupe-dashboard/hooks/useGetGroupStats.ts, source/sites/publicodes/App.tsx, source/sites/publicodes/Landing.tsx
=> Correctifs mode groupe 

source/sites/publicodes/pages/GuideGroupe.js
Suite de https://github.com/incubateur-ademe/nosgestesclimat/pull/2040
=> Modifie la clé pour accéder aux guides catégorisés

source/components/conversation/Conversation.tsx, source/components/conversation/Question.tsx, source/components/conversation/conversationUtils.ts, source/contexts/MatomoContext.tsx, source/locales/ui/ui-fr.yaml, source/sites/publicodes/App.tsx
=> 🐛  Active le tracking des pages questions

source/locales/units.yaml
Fix https://github.com/incubateur-ademe/nosgestesclimat/issues/2062
=> Fix: oubli de traduction de l'unité "nuits"

source/components/conversation/RuleInput.tsx, source/components/conversation/select/NumberedMosaic.tsx, source/components/conversation/select/SelectDevices.tsx
Quelques fix pour https://github.com/incubateur-ademe/nosgestesclimat/pull/2060
=> Fix mosaic features

.gitignore, dist/demo-iframe.html, dist/demo-iframeSimulation.html, source/Provider.tsx, source/components/Footer.tsx, source/components/IframeResizer.tsx, source/components/Logo.tsx, source/components/localisation/Localisation.tsx, source/components/localisation/LocalisationMessage.tsx, source/components/localisation/useLocalisation.ts, source/components/localisation/utils.ts, source/locales/ui/ui-en-us.yaml, source/locales/ui/ui-fr.yaml, source/reducers/rootReducer.ts, source/sites/publicodes/App.tsx, source/sites/publicodes/iframeSimulation.js, webpack.common.js
Suite au revert de #1302, cette PR permet d'ajouter la feature correctement dans master.
=> Nouvel Iframe de simulation V2

source/components/localisation/useLocalisation.ts
Suite à #1305, l'idée est de permettre de mettre à jour le state si la localisation est fixée en paramètre de localisation
=> Reset localisation for iframe with specific region

source/components/conversation/RuleInput.tsx, source/components/conversation/estimate/KmHelp/EditableRow.js, source/components/conversation/estimate/KmHelp/KmForm.tsx, source/components/conversation/estimate/KmHelp/index.tsx
Un oubli d'argument lié à un refacto dans la PR https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1178
=> fix: aides aux km avion et voiture réactivées
